name: brentlab_rnaseq_pipeline

dependencies:
   - R=3.2.1
   - covr
   - feature
   - glue
   - knitr
   - rmarkdown
   - testthat
   - tidyverse
   - optparse=1.3.2
   - xlsx=0.5.7
   - bioconductor-deseq2=1.10.1
   - bioconductor-edger=3.12.1
   - bioconductor-noiseq=2.30.0
   - python=2.7.12
   - pandas=0.20.3
   - pysam=0.11.0
   - pyyaml=3.12
   - openpyxl=2.5.0
   - xlrd=1.1.0
