name: brentlab_rnaseq_pipeline

channels:
   - conda-forge
   - bioconda
   - r

dependencies:
   - r=3.6.*
   - r-tidyverse=1.3.*
   - r-optparse=1.6.*
   - r-xlsx=0.6.*
   - bioconductor-deseq2=1.26.*
   - bioconductor-biobase=2.46.*
   - bioconductor-biobase >=2.46.*
   - bioconductor-biocgenerics >=0.32.*
   - bioconductor-biocparallel >=1.20.*
   - bioconductor-genefilter=1.68.*
   - bioconductor-geneplotter=1.64.*
   - bioconductor-genomicranges=1.38.*
   - bioconductor-iranges=2.20.*
   - bioconductor-s4vectors=0.24.*
   - bioconductor-summarizedexperiment=1.16.*
   - libgcc-ng>=7.3.0
   - libstdcxx-ng>=7.3.0
   - r-hmisc
   - r-locfit
   - r-rcpp>=0.11.0
   - r-rcpparmadillo
   - bioconductor-edger=3.28.*
   - bioconductor-limma=3.42.*
   - libgcc-ng>=7.3.0
   - libstdcxx-ng>=7.3.0
   - r-base=3.6.*
   - r-locfit
   - r-rcpp
   - bioconductor-noiseq
   - r-matrix=1.2.*
   - python=2.7.12
   - pandas=0.20.3
   - pysam=0.11.0
   - pyyaml=3.12
   - openpyxl=2.5.0
   - xlrd=1.1.0
