name: brentlab_rnaseq_pipeline

channels:
   - conda-forge
   - bioconda
   - r

dependencies:
   - r-tidyverse
   - r-optparse
   - r-xlsx
   - bioconductor-deseq2
   - bioconductor-edger
   - bioconductor-noiseq
   - python
   - pandas
   - pysam
   - pyyaml
   - openpyxl
   - xlrd
