TOTAL_READS:
  threshold: 5000000
  status: 1
COMPLEXITY:
  threshold: 0.8
  status: 2
MUT_FOW:
  DELETION:
    threshold: 0.1
    status: 4
  OVEREXPRESSION:
    threshold: 1.5
    status: 4
MARKER_FOM:
  threshold: 0.5
  status: 8
COV_MED:
  threshold: 0.25
  status: 16